version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: finance_db
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: finance_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - finance_network

volumes:
  postgres_data:

networks:
  finance_network:
    driver: bridge
